-- =========================================================
-- 5. GESTION DE UN VIVERO - Normalizado a 3FN
-- =========================================================
CREATE DATABASE IF NOT EXISTS gestion_vivero;
USE gestion_vivero;

CREATE TABLE SUELOS (
    SOIL_CATEGORY     CHAR(1) PRIMARY KEY,
    SOIL_DESCRIPTION  VARCHAR(50) NOT NULL
);

CREATE TABLE PLANTAS (
    PLANT_CODE     INT PRIMARY KEY,
    PLANT_NAME     VARCHAR(100) NOT NULL,
    SOIL_CATEGORY  CHAR(1) NOT NULL,
    FOREIGN KEY (SOIL_CATEGORY) REFERENCES SUELOS(SOIL_CATEGORY)
);

CREATE TABLE UBICACIONES (
    LOCATION_CODE  INT PRIMARY KEY,
    LOCATION_NAME  VARCHAR(100) NOT NULL
);

CREATE TABLE UBICACION_PLANTA (
    LOCATION_CODE  INT NOT NULL,
    PLANT_CODE     INT NOT NULL,
    PRIMARY KEY (LOCATION_CODE, PLANT_CODE),
    FOREIGN KEY (LOCATION_CODE) REFERENCES UBICACIONES(LOCATION_CODE),
    FOREIGN KEY (PLANT_CODE) REFERENCES PLANTAS(PLANT_CODE)
);

INSERT INTO SUELOS VALUES
('A','Sandstone'),
('B','Sandstone/limestone'),
('C','Limestone');

INSERT INTO PLANTAS VALUES
(431,'Leucadendron','A'),
(446,'Protea','B'),
(482,'Erica','C'),
(449,'Restio','B');

INSERT INTO UBICACIONES VALUES
(11,'Kirstenbosch Gardens'),
(12,'Karbonkelberg Mountains');

INSERT INTO UBICACION_PLANTA VALUES
(11,431),(11,446),(11,482),
(12,431),(12,449);
